# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{textfilter}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Grosser"]
  s.date = %q{2009-11-18}
  s.email = %q{grosser.michael@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "VERSION",
     "init.rb",
     "lib/text_filter.rb",
     "lib/text_filter.rb",
     "spec/models.rb",
     "spec/models.rb",
     "spec/spec_helper.rb",
     "spec/spec_helper.rb",
     "spec/text_filter_spec.rb",
     "spec/text_filter_spec.rb",
     "textfilter.gemspec"
  ]
  s.homepage = %q{http://github.com/grosser/textfilter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{ActiveRecord/Rails filter text fields before assigning them}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/text_filter_spec.rb",
     "spec/models.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
  end
end

